USE DB_QLCH_ADB1_14

--CHO DANH SÁCH CÁC HOÁ ĐƠN LẬP TRONG NĂM 2020
SELECT MAHD, NGAYLAP, TONGTIEN
FROM HOADON 
WHERE YEAR(NGAYLAP) = 2020
--CHO DANH SÁCH CÁC KHÁCH HÀNG Ở TPHCM
SELECT MAKH, HO +' '+ TEN as HOTEN, NGSINH, TPHO
FROM KHACHHANG
WHERE TPHO = N'TPHCM'
--CHO DANH SÁCH CÁC SẢN PHẨM CÓ GIÁ TRONG MỘT KHOẢNG TỪ___ ĐẾN ____(lay vd tu 100000 den 1000000)
SELECT MASP, TENSP, GIA 
FROM SANPHAM 
WHERE GIA BETWEEN 100000 AND 1000000
--CHO DANH SÁCH CÁC SẢN PHẨM CÓ SỐ LƯỢNG TỒN <100
SELECT MASP, TENSP, SOLUONGTON
FROM SANPHAM 
WHERE SOLUONGTON < 100
--CHO DANH SÁCH CÁC SẢN PHẨM BÁN CHẠY NHẤT(SỐ LƯỢNG BÁN NHIỀU NHẤT)
SELECT TOP 10 SP.MASP, SP.TENSP, SUM(CT.SOLUONG) AS SOLUONGBAN 
FROM SANPHAM SP JOIN CT_HOADON CT ON SP.MASP = CT.MASP
GROUP BY SP.MASP, SP.TENSP
ORDER BY SUM(CT.SOLUONG) DESC

--CHO DANH SÁCH CÁC SẢN PHẨM CÓ DOANH THU CAO NHẤT 
SELECT TOP 10 SP.MASP, SP.TENSP, SUM(CT.THANHTIEN) AS DOANHTHU
FROM SANPHAM SP JOIN CT_HOADON CT ON SP.MASP = CT.MASP
GROUP BY SP.MASP, SP.TENSP
ORDER BY SUM(CT.THANHTIEN) DESC