-- Bảng Tầm ảnh hưởng
/*

*/
CREATE TRIGGER THANHTIEN
ON CT_HOADON
FOR INSERT, UPDATE
AS
BEGIN
  UPDATE CT_HOADON
  SET CT_HOADON.THANHTIEN = (CT_HOADON.GIABAN - CT_HOADON.GIAGIAM) * CT_HOADON.SOLUONG
  FROM CT_HOADON
  INNER JOIN INSERTED T
    ON T.MAHD = CT_HOADON.MAHD
    AND T.MASP = CT_HOADON.MASP
END
GO

CREATE TRIGGER TONGTIEN
ON CT_HOADON
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  UPDATE HOADON
  SET HOADON.TONGTIEN = (SELECT
      SUM(THANHTIEN)
    FROM CT_HOADON
    WHERE CT_HOADON.MAHD = T.MAHD)
  FROM Inserted T
  JOIN HOADON
    ON HOADON.MAHD = T.MAHD
END
GO
